Change name from maesh to traefik mesh
layer5io/meshery-traefik-mesh pull request #64
Opened 2021-01-01 14:36 UTC by utkarsh-pro

**Description**
This PR changes he following:
1. Change name from maesh to traefik mesh at almost all of the places **except** the published docker images as they are controlled from github actions.
2. Enable creating namespace if the namespace doesn't already exists.

Tests done (within the container):
- [x] Installing and uninstalling traefik mesh
- [x] Installing and uninstalling sample app (emojivoto)

**Note for reviewers**

2021-01-01 18:23 UTC, leecalcote approved these changes
Very good!

2021-01-01 18:27 UTC, leecalcote commented
@utkarsh-pro we have a Kudo/kuttl issue to investigate - https://github.com/layer5io/meshery-traefik-mesh/pull/64/checks?check_run_id=1633826926

2021-01-01 19:35 UTC, leecalcote requested changes
A couple failing build checks to tend to...

2021-01-04 18:57 UTC, leecalcote commented
@ramrodo we might need some of the magic CI (go proxy) sprinkles here.

2021-01-04 19:11 UTC, ramrodo commented on Dockerfile
> +RUN GOPROXY=direct GOSUMDB=off go build -ldflags="-w -s" -a -o /meshery-traefik-mesh .
Right, here is the suggestion:

```suggestion
RUN GOPROXY=https://proxy.golang.org GOSUMDB=off go build -ldflags="-w -s" -a -o /meshery-traefik-mesh .
```

2021-01-04 20:40 UTC, leecalcote commented on Dockerfile
> +RUN GOPROXY=direct GOSUMDB=off go build -ldflags="-w -s" -a -o /meshery-traefik-mesh .
thank you, thank you

2021-01-05 06:26 UTC, leecalcote commented
Green checkmarks! 😅 Thank you, @ramrodo

2021-01-05 06:26 UTC, merged